### ISSUE TITLE
Husky post install script breaks npm install in backstage

### ISSUE THREAD

**Issue by baldm** [Parsifal-M/backstage-dev-quotes#49]
Hello, im using your plugin for backstage, but husky is currently breaking my install process.
when i run `npm install` in my backstage project i get an error from husky originating from this repo:

```
npm error code 127
npm error path /Users/username/Projects/backstage/node_modules/@parsifal-m/plugin-dev-quotes-homepage
npm error command failed
npm error command sh -c husky install
npm error sh: husky: command not found
```

I think this error was introduced 5 days ago in this commit, possibly from the post install script:
https://github.com/Parsifal-M/backstage-dev-quotes/commit/e430d1620dd61285f81aa37a007530471ae567ee

**Comment by Parsifal-M** [comment]
> Hello, im using your plugin for backstage, but husky is currently breaking my install process. when i run `npm install` in my backstage project i get an error from husky originating from this repo:
> 
> ```
> npm error code 127
> npm error path /Users/username/Projects/backstage/node_modules/@parsifal-m/plugin-dev-quotes-homepage
> npm error command failed
> npm error command sh -c husky install
> npm error sh: husky: command not found
> ```
> 
> I think this error was introduced 5 days ago in this commit, possibly from the post install script: [e430d16](https://github.com/Parsifal-M/backstage-dev-quotes/commit/e430d1620dd61285f81aa37a007530471ae567ee)

Hey!

Thanks for reporting this, I will have a look into it! Just curious do you mean `yarn install`? AFAIK you should be using `yarn` with Backstage 🤔

**Comment by baldm** [comment]
Welp, you are completely right. `npm install` will attempt to run the post install script while `yarn install` will not. 
This fixes the issue I'm having so i will close the issue!
